// // This file is automatically generated. Do not edit it directly.
// import { createClient } from '@supabase/supabase-js';
// import type { Database } from './types';

// const SUPABASE_URL = "https://ndypurygmnkxxgiozldm.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5keXB1cnlnbW5reHhnaW96bGRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NTU2MDQsImV4cCI6MjA2NjQzMTYwNH0.eLWlPsQgWaQjiALJF5dpf3wsJgav-FSY5QWnlzMnlvQ";

// // Import the supabase client like this:
// // import { supabase } from "@/integrations/supabase/client";

// export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = process.env.REACT_APP_SUPABASE_URL! as string;
const SUPABASE_PUBLISHABLE_KEY = process.env.REACT_APP_SUPABASE_ANON_KEY! as string;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
//   throw new Error('Missing Supabase environment variables');
// }

// Create client with additional options for better error handling
// export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
//   auth: {
//     persistSession: true,
//     autoRefreshToken: true,
//     detectSessionInUrl: true
//   },
//   global: {
//     headers: {
//       'Content-Type': 'application/json'
//     }
//   }
// });