// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndypurygmnkxxgiozldm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5keXB1cnlnbW5reHhnaW96bGRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NTU2MDQsImV4cCI6MjA2NjQzMTYwNH0.eLWlPsQgWaQjiALJF5dpf3wsJgav-FSY5QWnlzMnlvQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);